name: my_first_app
description: "A new Flutter project."

# Prevent accidental publish to pub.dev
publish_to: "none"

# App version
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: ">=3.0.0 <4.0.0"

# ---------------- Dependencies ----------------
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  share_plus: ^7.2.2 # ✅ Package for sharing (WhatsApp, Telegram, Email, etc.)

# ---------------- Dev Dependencies ----------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ---------------- Flutter Section ----------------
flutter:
  uses-material-design: true

  # Uncomment and add assets if needed
  # assets:
  #   - images/

  # Uncomment and add fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
